force-app/objects/Maintenance__c.object
<CustomObject>
    <description>Représente une réparation de bateau</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>Date de fin de la maintenance</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Daet de debut de la maintenance</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <description>Etat de la maintenance</description>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>En cours</fullName>
                </value>
                <value>
                    <fullName>Traité</fullName>
                </value>
                <value>
                    <fullName>Abandonné</fullName>
                </value>
                <value>
                    <fullName>Planifiée</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Maintenance</label>
    <nameField>
        <label>Maintenance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maintenances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/service/MaintenanceService.cls
public with sharing class MaintenanceService {

    
    // methode pour creer une maintenance
    public static Maintenance__c newMaintenance(Maintenance__c maintenance){
        maintenance.StartDate__c = Date.today();
        insert maintenance;
        return maintenance;
    }

    // methode pour terminer une maintenance
    public static Boolean endMaintenance(Id maintenanceId, String status){
        try {
            update new Maintenance__c(
                Id = maintenanceId,
                Statut__c = status,
                EndDate__c = Date.today()
            );
            return true;
        } catch (Exception e){
            return false;
        }

    }


}