force-app/objects/Maintenance__c.object
<CustomObject>
    <description>Représente une réparation de bateau</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>Date de fin de la maintenance</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Daet de debut de la maintenance</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <description>Etat de la maintenance</description>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>En cours</fullName>
                </value>
                <value>
                    <fullName>Traité</fullName>
                </value>
                <value>
                    <fullName>Abandonné</fullName>
                </value>
                <value>
                    <fullName>Planifiée</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Maintenance</label>
    <nameField>
        <label>Maintenance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maintenances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/job/MaintenanceStatusJobTest.cls
@isTest
public with sharing class MaintenanceStatusJobTest {
    
    @isTest public static void testBatch(){
        //given
        Maintenance__c maint = new Maintenance__c();
        maint.StartDate__c = Date.newInstance(2022, 05, 02);
        maint.EndDate__c = Date.newInstance(2022, 05, 30);
        maint.Statut__c  = 'En cours';
        insert maint;

        //when
        Test.startTest();
        MaintenanceStatusJob myBatchObject = new MaintenanceStatusJob();
        Id batchId = Database.executeBatch(myBatchObject, 1000);
        Test.stopTest();
        
        //then
        Maintenance__c maintenance = [SELECT Id, Statut__c FROM Maintenance__c WHERE Id = :maint.Id LIMIT 1];
        
        System.assertEquals('En cours', maintenance.Statut__c, 'Le statut est en cours');
    


    }

    @isTest public static void badEndDate(){
        //given
        Maintenance__c maint = new Maintenance__c();
        maint.StartDate__c = Date.newInstance(2022, 04, 20);
        maint.EndDate__c = Date.newInstance(2022, 05, 01);
        maint.Statut__c  = 'En cours';
        MaintenancesTriggerHandler.BYPASS = true;
        insert maint;

        //when
        Test.startTest();
        MaintenanceStatusJob myBatchObject = new MaintenanceStatusJob();
        Id batchId = Database.executeBatch(myBatchObject, 1000);
        Test.stopTest();
        
        //then
        Maintenance__c maintenance = [SELECT Id, Statut__c FROM Maintenance__c WHERE Id = :maint.Id LIMIT 1];
        
        System.assertEquals('Traité', maintenance.Statut__c, 'Le statut est traitée');
    


    }
}