force-app/objects/Maintenance__c.object
<CustomObject>
    <description>Représente une réparation de bateau</description>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>Date de fin de la maintenance</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Statut__c</fullName>
        <description>Etat de la maintenance</description>
        <label>Statut</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>En cours</fullName>
                </value>
                <value>
                    <fullName>Traité</fullName>
                </value>
                <value>
                    <fullName>Abandonné</fullName>
                </value>
                <value>
                    <fullName>Planifiée</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Maintenance</label>
    <nameField>
        <label>Maintenance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maintenances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/job/MaintenanceStatusJob.cls
public with sharing class MaintenanceStatusJob implements Database.Batchable<SObject> {
    

    public Database.QueryLocator start(Database.BatchableContext bc) {
        // collect the batches of records or objects to be passed to execute
        return Database.getQueryLocator(
            'SELECT Id, EndDate__c FROM Maintenance__c WHERE Statut__c = \'En cours\' AND EndDate__c < TODAY' 
        );
    }

    /**
     * On veut changer le statut des maintenances dont la date de fin de maintenance est passee
     */
    public void execute(Database.BatchableContext bc, List<Maintenance__c> records){
        // process each batch of records>();
        for(Maintenance__c maintenance : records) {
            maintenance.Statut__c = 'Traité'; 
        }
        update records;
    }

    
    public void finish(Database.BatchableContext bc){
        // execute any post-processing operations
        // debug
        // mail erreur
        // retry
    }



}